import React, { useState } from "react";
import axios from "axios";

function DiseasePredict() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedFile(file);
      setPreview(URL.createObjectURL(file));
      setResult(null);
      setError(null);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!selectedFile) return;

    setLoading(true);
    setError(null);
    const formData = new FormData();
    formData.append("file", selectedFile);

    try {
      const res = await axios.post(
        "http://127.0.0.1:8000/api/predict-disease",
        formData
      );
      setResult(res.data.prediction_text);
    } catch (err) {
      setError("Failed to analyze image. Please try again.");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page-container">
      <h1>🍂 Disease Detection</h1>
      <p className="page-description">
        Upload a high-resolution photo of a plant leaf to identify diseases
        using our Convolutional Neural Network (CNN) model.
      </p>

      <form
        onSubmit={handleSubmit}
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: "20px",
        }}
      >
        <div
          className="form-group"
          style={{ width: "100%", maxWidth: "400px" }}
        >
          <label>Select Leaf Image</label>
          <input
            type="file"
            accept="image/*"
            onChange={handleFileChange}
            style={{ border: "none", padding: "10px 0" }}
          />
          <span className="form-hint">Supported formats: JPG, PNG, JPEG</span>
        </div>

        {preview && (
          <div
            style={{ position: "relative", width: "100%", maxWidth: "400px" }}
          >
            <img
              src={preview}
              alt="Preview"
              style={{
                width: "100%",
                borderRadius: "12px",
                border: "2px solid var(--primary-color)",
              }}
            />
          </div>
        )}

        <button
          type="submit"
          className="form-button"
          disabled={!selectedFile || loading}
          style={{ maxWidth: "400px" }}
        >
          {loading ? "Analyzing Image..." : "Identify Disease"}
        </button>
      </form>

      {error && <div className="error-box">{error}</div>}

      {result && (
        <div className="result-box result-box-success">
          <p>Analysis Result:</p>
          <h2>{result}</h2>
          <p
            style={{
              fontSize: "0.9rem",
              marginTop: "10px",
              color: "var(--text-light)",
            }}
          >
            Note: Results are generated by AI. Consult an expert for critical
            decisions.
          </p>
        </div>
      )}
    </div>
  );
}

export default DiseasePredict;
